### ISSUE TITLE
ERROR 500 I Just upgrade my module to 1.0.6 I've received this error on LWC 3.6.4

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-pgrouting-module#40]
Error 500. A technical error has occured. Sorry for this trouble.

mapBuilder/urls.xml: include file urls.xml of the module pgrouting does not exist (<url include="urls.xml" module="pgrouting" pathinfo="/pgrouting"/>)

I've tried to reconfigure mapBuilder, mapBuilderAdmin and LCW but the result is the same
_php configurator.php mapBuilder
Configuration migration is starting
Configuration migration is finished
Configuration is starting
All modules dependencies are ok
Configuration starts
Modules are configured
Configuration is finished_

_php configurator.php mapBuilderAdmin
Configuration migration is starting
Configuration migration is finished
Configuration is starting
All modules dependencies are ok
Configuration starts
Modules are configured
Configuration is finished_

_sudo php installer.php
Installation is starting
All modules dependencies are ok
Installation starts
Module mapBuilder upgraded to the version 2.1.1
Module mapBuilderAdmin upgraded to the version 2.1.1
All modules are installed or upgraded
Installation is finished_

_php configurator.php
Configuration migration is starting
Configuration migration is finished
Configuration is starting
All modules dependencies are ok
Configuration starts
Configuration of the module jelix
Configuration of the module jcommunity
Configuration of the module jacl2
Configuration of the module jacl2db
Configuration of the module master_admin
Configuration of the module jauthdb_admin
Configuration of the module jacl2db_admin
Configuration of the module admin
Configuration of the module lizmap
Configuration of the module mapBuilder
Configuration of the module mapBuilderAdmin
Configuration of the module wps
Configuration of the module pgrouting
SRID your are using? (default is '32633') > 
PostgreSQL group of user to grant access on the schema pgrouting ? > lizmap
Which is the type of your database?  (default is 'pgsql')
  [0] mssql
  [1] mysqli
  [2] oci
  [3] pgsql
  [4] sqlite3
  [5] sqlsrv_
 > 
_Use a PDO to connect to the database? ( 'y' or 'n', default is n) > y
For all tables accessible from this connection, are they name prefixed? ( 'y' or 'n', default is n) > n
Configuration of the module view
Configuration of the module action
Configuration of the module proj4php
Configuration of the module dynamicLayers
Configuration of the module filter
Configuration of the module dataviz
Modules are configured
Configuration is finished_

_Installation is starting
All modules dependencies are ok
Installation starts
All modules are installed or upgraded
Installation is finished_

**Comment by Antoviscomi** [comment]
I have also Try to configure LWC without mapBuilder with no results so my LWC it's now down

**Comment by Antoviscomi** [comment]
Also the configuration without pgrouting module on give me the same error

**Comment by Antoviscomi** [comment]
I clean all older pgrouting packages in my lizmap folder, then I reinstall pgrouting by compoer the it works fine now

**Comment by Gustry** [comment]
Thanks for debugging.
You can still share command next time you have used to clean etc, it might help others.

**Comment by Antoviscomi** [comment]
@Gustry Yes of course, I'd simply erased all previous pgrouting folders (0.3.1 version) from 
1 - ./lizmap/my-packages;
2 - ./lizmap/lizmap-modules;
3 - ./lizmap/modules;
then I get a new fresh copy by composer (1.0.6 version), configured and install it, clean-vartmp ant set rights.
all works  fine now
