### ISSUE TITLE
Problems installing and configuring the module

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-pgrouting-module#46]
Trying to follow documentation here

https://github.com/3liz/lizmap-pgrouting-module/blob/master/docs/installation.md

1) while trying to install the module without using composer an error is returned

```
php lizmap/install/configurator.php pgrouting
Configuration migration is starting
Configuration migration is finished

In ModuleInfos.php line 113:

  No module.xml file into /home/gmanghi/www/naturalgis_demo/lizmap/lizmap-modules/pgrouting/


configure [-p|--parameters PARAMETERS] [-r|--remove] [-f|--force] [-e|--entry-points ENTRY-POINTS] [--] [<module>]
```

2) installation with composer seems to work, anyway running the "configurator.php" script as described here

https://github.com/3liz/lizmap-pgrouting-module/blob/master/docs/installation.md#launching-the-installer-with-lizmap-web-client-36

do not ask "all parameters for the PostgreSQL database access", just the other infos (SRID, role, etc.), so the next step

`php lizmap/install/installer.php`

fails with 

```
Installation is starting
All modules dependencies are ok
Installation starts
[error] An error occured during the installation of the module pgrouting: error during the connection localhost
Installation is finished
```

I'm using LMWC 3.6.9 and PHP 8.1 and the doubt is if the path to follow is the one described in "Launching the installer with Lizmap Web Client 3.6"

https://github.com/3liz/lizmap-pgrouting-module/blob/master/docs/installation.md#launching-the-installer-with-lizmap-web-client-36

or in "Launching the installer with Lizmap 3.5"

https://github.com/3liz/lizmap-pgrouting-module/blob/master/docs/installation.md#launching-the-installer-with-lizmap-35

because the latter also says "_If you are using Lizmap Web Client 3.6 or higher..._" as the former, but maybe this just an error in the docs(?).

Any help is much appreciated.

**Comment by laurentj** [comment]
Hi,

>while trying to install the module without using composer an error is returned
> ...  No module.xml file into /home/gmanghi/www/naturalgis_demo/lizmap/lizmap-modules/pgrouting/ ...

It seems you didn't copy all files from the [pgrouting directory](https://github.com/3liz/lizmap-pgrouting-module/tree/master/pgrouting).

>do not ask "all parameters for the PostgreSQL database access", just the other infos (SRID, role, etc.),

The documentation was not updated. It doesn't ask any postgresql parameters. After launching `configurator.php`, you should indicate all postgresql access parameters into the `lizmap/var/config/profiles.ini.php` file, into a `[jdb:pgrouting]`, as indicating into the installation documentation with lizmap 3.5. Then you can launch `installer.php`.

I will update the documentation.

**Comment by laurentj** [comment]
I fixed all issues into the documentation. Thanks for your report.

**Comment by gioman** [comment]
> I fixed all issues into the documentation. Thanks for your report.

@laurentj thanks! do you have the shapefile referred here? https://github.com/3liz/lizmap-pgrouting-module/issues/47 if yes I can make a PR against the docs so to add the "create table..." in the SQL code.
